# Copyright (c) 2026 Winthir Studios.
# Licensed under the Business Source License 1.1 — see LICENSE.txt.
# Converts to Apache License 2.0 on 2030-07-27.
"""Build a standalone polytess executable (PyInstaller, one-dir).

    python build_exe.py [--no-custom-library] [--no-plugins]

Produces ``dist/exe/polytess/`` containing the GUI executable
(``polytess``) and the headless CLI (``polytess-cli``), then zips it as
``dist/polytess-<version>-<os>-<arch>.zip``. No Python required on the
target machine. Bundles plain Python source (BUSL — no IP-protection
compilation step). Platform rules: build on the OS you target.

Only SHIPPED_PLUGINS are ever bundled, regardless of what else happens
to sit under plugins/ locally (e.g. private example plugins you're
developing) — this is the enforcement point for "only the base + the
example plugin ship"."""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.abspath(__file__))
EXE_DIR = os.path.join(ROOT, "dist", "exe")

# the only plugin(s) a build may bundle — see module docstring
SHIPPED_PLUGINS = ["simpack_template"]

# modules invisible to PyInstaller's import analysis: lazily imported, or
# loaded as folder plugins at runtime
HIDDEN = ["qasync", "cryptography", "cryptography.hazmat.primitives."
          "asymmetric.ed25519", "reportlab", "polytess",
          "polytess.cli", "polytess.gui.main_window"]
COLLECT_ALL = ["polytess", "reportlab"]


def build(no_custom: bool, no_plugins: bool) -> str:
    sys.path.insert(0, ROOT)
    from polytess import __version__

    launcher = os.path.join(ROOT, "build", "exe_launcher_gui.py")
    cli_launcher = os.path.join(ROOT, "build", "exe_launcher_cli.py")
    os.makedirs(os.path.dirname(launcher), exist_ok=True)
    with open(launcher, "w", encoding="utf-8") as fh:
        fh.write("import sys\nfrom polytess.__main__ import main\n"
                 "sys.exit(main())\n")
    with open(cli_launcher, "w", encoding="utf-8") as fh:
        fh.write("import sys\nfrom polytess.cli import main\n"
                 "sys.exit(main())\n")

    datas = [(os.path.join(ROOT, "polytess", "assets"),
              os.path.join("polytess", "assets"))]
    if not no_plugins:
        for name in SHIPPED_PLUGINS:
            source = os.path.join(ROOT, "plugins", name)
            if os.path.isdir(source):
                datas.append((source, os.path.join("plugins", name)))
    if not no_custom:
        source = os.path.join(ROOT, "custom_instructions")
        if os.path.isdir(source):
            datas.append((source, "custom_library"))
    datas.append((os.path.join(ROOT, "LICENSE.txt"), "."))

    from PyInstaller.building.build_main import main as pyinstaller_main  # noqa
    spec = os.path.join(ROOT, "build", "polytess_exe.spec")
    windowed = "console=False" if sys.platform != "linux" else "console=True"
    with open(spec, "w", encoding="utf-8") as fh:
        fh.write(f"""# generated by build_exe.py
from PyInstaller.utils.hooks import collect_all

hidden = {HIDDEN!r}
datas = {datas!r}
binaries = []
for package in {COLLECT_ALL!r}:
    d, b, h = collect_all(package)
    datas += d; binaries += b; hidden += h

analysis_gui = Analysis([{launcher!r}], pathex=[{ROOT!r}],
                        datas=datas, binaries=binaries,
                        hiddenimports=hidden, noarchive=False)
pyz_gui = PYZ(analysis_gui.pure)
exe_gui = EXE(pyz_gui, analysis_gui.scripts, [], exclude_binaries=True,
              name="polytess", {windowed}, upx=False)

analysis_cli = Analysis([{cli_launcher!r}], pathex=[{ROOT!r}],
                        hiddenimports=hidden, noarchive=False)
pyz_cli = PYZ(analysis_cli.pure)
exe_cli = EXE(pyz_cli, analysis_cli.scripts, [], exclude_binaries=True,
              name="polytess-cli", console=True, upx=False)

coll = COLLECT(exe_gui, analysis_gui.binaries, analysis_gui.datas,
               exe_cli, analysis_cli.binaries, analysis_cli.datas,
               name="polytess")
""")
    shutil.rmtree(os.path.join(EXE_DIR, "polytess"), ignore_errors=True)
    subprocess.run([sys.executable, "-m", "PyInstaller", "--noconfirm",
                    "--distpath", EXE_DIR,
                    "--workpath", os.path.join(ROOT, "build", "pyinstaller"),
                    spec], check=True, cwd=ROOT)

    tag = f"{__version__}-{sys.platform}-{platform.machine()}"
    zip_path = os.path.join(ROOT, "dist", f"polytess-{tag}.zip")
    bundle = os.path.join(EXE_DIR, "polytess")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for dirpath, _dirnames, filenames in os.walk(bundle):
            for name in filenames:
                full = os.path.join(dirpath, name)
                zf.write(full, os.path.join(
                    "polytess", os.path.relpath(full, bundle)))
    size = os.path.getsize(zip_path) / 1024 / 1024
    print(f"executable bundle: {bundle}")
    print(f"zip: {zip_path}  ({size:.1f} MB)")
    return zip_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-custom-library", action="store_true",
                        help="leave custom_instructions/ out (public "
                             "release artifacts)")
    parser.add_argument("--no-plugins", action="store_true",
                        help="core only, no plugins")
    args = parser.parse_args()
    build(args.no_custom_library, args.no_plugins)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
